project:
  type: book
  output-dir: docs

book:
  title: "Computer Vision: Object Detection using Faster R-CNN, Mask R-CNN, and YOLOv8"
  subtitle: "University of West Florida"
  author:
    - "Project Lead: Hector R. Gavilanes"
    - "Deep Learning Architect: Jacob Knight"
    - "Data Scientist: Kyle Knuth"
    - "Software Engineer: Sai Devarashetty"
    - "Software Engineer: Sai Meghana"
  date: "February 16, 2024"
  repo-url: https://github.com/kimerared/R-CNN.git
  downloads: [pdf]

  chapters:
    - cover.qmd
    - index.qmd
    - glossary.qmd
    - summary.qmd
    - intro.qmd
    - Literature-Review.qmd
    - methodology.qmd
    - analysis.qmd
    - results.qmd
    - conclusion.qmd
    - references.qmd
  appendices: 
    - contributions.qmd
    - documentation.qmd

bibliography: references.bib
csl: https://www.zotero.org/styles/ieee-with-url

format:
  html:
    theme: cosmo
    page-layout: full
  pdf:
    documentclass: scrreprt

editor: visual
reference-location: section
