project:
  type: book
  output-dir: docs

book:
  title: "Computer Vision: Exploring Object Detection and Segmentation using Faster R-CNN, Mask R-CNN, and YOLOv8"
  subtitle: "A Comparative Analysis"
  favicon: 'book-favicon-512.png'
  author:
    - "Hector R. Gavilanes, Project Lead"
    - "Jacob Knight, Deep Learning Architect"
    - "Kyle Knuth, Data Scientist"
    - "Sai Devarashetty, Software Engineer"
  date: "February 16, 2024"
  repo-url: https://github.com/kimerared/R-CNN.git
  description: "Exploring Object Detection and Segmentation using Faster R-CNN, Mask R-CNN, and YOLOv8 - Online report."

  chapters:
    - index.qmd
    - cover.qmd
    - glossary.qmd
    - summary.qmd
    - intro.qmd
    - Literature-Review.qmd
    - methodology.qmd
    - analysis.qmd
    - results.qmd
    - videos.qmd
    - conclusion.qmd
    - references.qmd
  appendices: 
    - yolov9.qmd
    - contributions.qmd
    - resources.qmd

bibliography: references.bib
csl: https://www.zotero.org/styles/ieee-with-url

format:
  html:
    theme: cosmo
    page-layout: full
    citation-location: margin
  pdf:
    documentclass: scrreprt
    reference-location: document
    
editor: visual

