project:
  type: book
  output-dir: docs

book:
  title: "Computer Vision Object Detection"
  subtitle: "Using Faster R-CNN, Mask R-CNN, and YOLOv8"
  author:
    - "Project Lead: Hector R. Gavilanes"
    - "Deep Learning Architect: Jacob Knight"
    - "Data Scientist: Kyle Knuth"
    - "Software Engineer: Sai Meghana"
  date: "2/16/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - Literature-Review.qmd
    - methodology.qmd
    - analysis.qmd
    - results.qmd
    - conclusion.qmd
    - references.qmd
  appendices: 
    - contributions.qmd

bibliography: references.bib
csl: https://www.zotero.org/styles/ieee-with-url

format:
  html:
    theme: cosmo
    page-layout: full
  pdf:
    documentclass: scrreprt

editor: visual

