---
jupyter: python3
---

# Conclusion

In conclusion, our aim in this project was to thoroughly examine the Faster R-CNN method, alonside an exploration of alternatives like Mask R-CNN and YOLOv8. Our analysis clearly shows that both Mask R-CNN and YOLOv8 outperform Faster R-CNN in terms of spotting objects accurately, and inference time.

YOLOv8 stands out for its ability to detect objects in real-time situations. On the other hand, Mask R-CNN shines when it comes to accurately identifying objects in images and videos, especially when it requires understanding detailed object shapes and boundaries.

However, it's worth noting that Mask R-CNN's performance might rely heavily on having enough computing power because it needs more processing resources compared to YOLOv8. This highlights the importance of not only considering performance but also practical concerns and limitations when choosing a model for real-world applications.

In conclusion, our research offers insight on the strengths and weaknesses of different object detection methods. By providing practical insights, we believe that YOLOv8 algorithm offers a good trade-off between detection performance, and inference time.

## Future Studies

Expanding upon the current research, future investigations could delve into the utilization of auto-annotated classes generated by SAM to enrich the COCO dataset with a diverse range of object classes. This expansion could provide valuable insights into the performance of the model when confronted with multiple classes, potentially enhancing its overall accuracy and robustness.

Moreover, to further extend the scope of this study, it would be beneficial to implement the YOLOv9 model and compare its performance against its predecessor, YOLOv8. This comparative analysis could reveal advancements and enhancements in real-time inference capabilities attained with the latest version of the YOLO model.

The dynamic field of computer vision provides diverse unexplored paths and untapped research potential. As technology progresses, it becomes increasingly important to refine these methodologies through researchers' contributions to address the evolving demands of various real-world applications.
